package net.raebu.raebumod.entity.client.Maushold3;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class Maushold3Animations {
        public static final Animation ANIM_MAUSHOLD3_IDLE = Animation.Builder.create(1.5F).looping()
                        .addBoneAnimation("Body", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("Left_Arm", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -5.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .addBoneAnimation("Right_Arm", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .addBoneAnimation("Body4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("right_arm4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .addBoneAnimation("left_arm4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -5.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .addBoneAnimation("Body2", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(2.5F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("left_arm2", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -5.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .addBoneAnimation("right_arm2", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR)))
                        .build();

        public static final Animation ANIM_MAUSHOLD3_RUN = Animation.Builder.create(1.5F).looping()
                        .addBoneAnimation("Left_Arm", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("Right_Arm", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("left_leg", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("right_leg", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("left_leg4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("right_leg4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(-10.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("right_arm4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, -10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("left_arm4", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.2083F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.4583F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.7083F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.9583F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 10.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.2083F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("left_leg2", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .addBoneAnimation("right_leg2", new Transformation(Transformation.Targets.ROTATE,
                                        new Keyframe(0.0F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.25F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.5F, AnimationHelper.createRotationalVector(0.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(0.75F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.0F, AnimationHelper.createRotationalVector(5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC),
                                        new Keyframe(1.25F, AnimationHelper.createRotationalVector(-5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.LINEAR),
                                        new Keyframe(1.5F, AnimationHelper.createRotationalVector(5.0F, 0.0F, 0.0F),
                                                        Transformation.Interpolations.CUBIC)))
                        .build();
}
